import type { Metadata } from 'next'
import { Inter, Actor } from 'next/font/google'
import './globals.css'
import Header from '@/components/header'
import Footer from '@/components/footer'

// const inter = Inter({ subsets: ['latin'] })
// const actor = Actor({ weight: ['400'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Clueless',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
